name: test
on: push

env:
  NORMAL_STRING: normalString
  NORMAL_NUMBER: 8
  NORMAL_NUMBER_0: 0
  NORMAL_NULL: null
  NORMAL_BOOL: false
  EXP_STR: ${{ 'str' }}
  EXP_NUMBER: ${{ 8 }}
  EXP_NUMBER_0: ${{ 0 }}
  EXP_BOOL: ${{ false }}
  EXP_NULL: ${{ null }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test NORMAL_NULL
        if: ${{ env.NORMAL_NULL == null }}
        run: echo "true"
      - name: test EXP_NULL
        if: ${{ env.EXP_NULL == null }}
        run: echo "true"
      - name: test EXP_NULL empty
        if: ${{ env.EXP_NULL == '' }}
        run: echo "true"
      - name: test2
        if: ${{ env.NORMAL_BOOL == 'false' }}
        run: echo "true"
      - name: test3
        if: ${{ env.EXP_BOOL == false }}
        run: echo "true"
      - run: echo "log ${{ env.unexisted || false }}"
      - run: echo "log NORMAL_STRING ${{ env.NORMAL_STRING }}"
      - run: echo "log NORMAL_NUMBER ${{ env.NORMAL_NUMBER }}"
      - run: echo "log NORMAL_NUMBER calc ${{ env.NORMAL_NUMBER_0 || 9 }}"
      - run: echo "log BOOL ${{ false }}"
      - run: echo "log NORMAL_BOOL ${{ env.NORMAL_BOOL }}"
      - run: echo "log EXP_BOOL ${{ env.EXP_BOOL }}"
      - run: echo "log NORMAL_BOOL calc ${{ env.NORMAL_BOOL || 2 }}"
      - run: echo "log EXP_NUMBER ${{ env.EXP_NUMBER }}"
      - run: echo "log EXP_NUMBER calc 2 ${{ env.EXP_NUMBER_0 || 2 }}"
      - run: echo "log null ${{ null }}"
      - run: echo "log null calc ${{ null || 2 }}"
      - run: echo "log null calc2 ${{ env.EXP_NULL || 2 }}"
      - run: echo "log UNEXISTED ${{ env.UNEXISTED }}"
      - run: echo "log UNEXISTED calc ${{ env.UNEXISTED || 4 }}"
      - run: echo "log 0 || 9 ${{ 0 || 9 }}"
      - run: echo "--------- ${{ 0 || 'asdsad' }}"
      - run: echo "log false || 9 ${{ false || 'asdsadsa' }}"
      - run: echo "log null || 9 ${{ null || 9 }}"
      - run: echo "log bool vs str || 9 ${{ false && '9' }}"


